name: dio_flutter_example
description:  Demonstrates how to use the dio package.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio:
    path: ../dio

dev_dependencies:
  lints: any

flutter:
  uses-material-design: true
