name: 'coverage_comment'

on:
  workflow_run:
    workflows: ['Verify packages abilities']
    types:
      - completed

jobs:
  download_coverage:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: tests.yml
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: code-coverage-results.md
      - name: Add PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.workflow_run.pull_requests[0].number }}
          recreate: true
          path: code-coverage-results.md
