name: Verify packages abilities

on:
  push:
    branches:
      - main
      - '6.0.0'
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - '6.0.0'
    paths-ignore:
      - "**.md"

# Ensure that new pushes/updates cancel running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  workflows:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [ min, current, max ]
    env:
      TEST_PRESET: all
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config
        with:
          flavor: ${{ matrix.flavor }}
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config.outputs.FLUTTER_CHANNEL }}
      - run: |
          chmod +x ./scripts/prepare_pinning_certs.sh
          ./scripts/prepare_pinning_certs.sh
      - name: Install proxy for tests
        run: sudo apt-get update && sudo apt-get install -y squid
      - run: dart pub get
      - name: Setup Melos SDK path
        run: echo "MELOS_SDK_PATH=${{ evn.FLUTTER_ROOT }}" >> $GITHUB_ENV
      - uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: false
      - name: Check satisfied packages
        run: |
          dart ./scripts/melos_packages.dart
          echo $(cat .melos_packages) >> $GITHUB_ENV
      - name: Melos Bootstrap
        run: melos bootstrap
      - name: '[Verify step] Format'
        if: ${{ matrix.flavor == 'current' }}
        run: melos run format
      - name: '[Verify step] Analyze packages'
        if: ${{ matrix.flavor == 'current' }}
        run: melos run analyze
      - name: '[Verify step] Publish dry-run'
        if: ${{ matrix.flavor == 'current' }}
        run: melos run publish-dry-run
      - name: '[Verify step] Test Dart packages [VM]'
        run: melos run test:vm
      - name: '[Verify step] Test Dart packages [Chrome]'
        run: melos run test:web:chrome
      - name: '[Verify step] Test Dart packages [Firefox]'
        run: melos run test:web:firefox
      - name: '[Verify step] Test Flutter packages'
        run: melos run test:flutter
      - name: '[Coverage] Format & print test coverage'
        if: ${{ matrix.flavor == 'current' }}
        run: melos run coverage:show
      - name: '[Coverage] Coverage Report'
        uses: clearlyip/code-coverage-report-action@v4
        if: ${{ matrix.flavor == 'current' && github.actor != 'dependabot[bot]'}}
        with:
          artifact_download_workflow_names: 'tests,coverage_base'
          filename: 'coverage/cobertura.xml'
