name: Publish Test Report

on:
  workflow_run:
    workflows:
      - 'Dio'
      - 'Example'
      - 'Cookie Manager'
      - 'HTTP2 Adapter'
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish test reports
        uses: dorny/test-reporter@v1
        with:
          name: ${{ github.event.workflow_run.workflow.name }} Test results
          artifact: test-results
          path: '**/*.json'
          reporter: dart-json
